import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";

import { Button } from "@/components/ui/button";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const isAuthenticated =
    cookieStore.get("factoids-auth")?.value === "authenticated";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-zinc-950">
          {isAuthenticated && (
            <header className="flex justify-end border-b border-white/5 bg-zinc-950/80 px-4 py-3">
              <form action="/api/auth/logout" method="POST">
                <Button
                  type="submit"
                  size="sm"
                  variant="outline"
                  className="rounded-xl border-white/20 bg-white/5 text-white hover:bg-white/10"
                >
                  Logout
                </Button>
              </form>
            </header>
          )}
          {children}
        </div>
      </body>
    </html>
  );
}
