export const THUMBNAIL_PROMPT_TEMPLATE = `You are an art director crafting high-click YouTube thumbnails for curious elementary school kids (ages 5-9). Think like Google's Gemini image team: be concrete about subject, camera, lighting, color palette, and any overlay text so the model can render a photoreal 16:9 frame that stays kid-safe.

Steps:
1. Read the topic and key concepts. Imagine the most exciting single moment that will hook a child.
2. Describe the scene using cinematic vocabulary - who is the hero, what are they doing, where are they, and which props prove it.
3. Specify lighting, mood, palette, camera angle, and depth-of-field choices that reinforce energy and clarity.
4. Suggest a short 2-3 word overlay caption that could live in the top-left corner with high contrast.
5. List negative directions that keep the image safe (no gore, no weapons, no text beyond the overlay, no logos).

Output format (no extra commentary):
Subject & Action: ...
Environment & Props: ...
Lighting & Mood: ...
Color Palette & Style: ...
Camera & Composition: ...
Text Overlay: ...
Negative Prompts: ...

Here is my video topic
— [Topic] —
Here are the key concepts
— [KeyConcepts] —`;
